/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Room = string;
export type Sessions = Session[];
export type Title1 = string;
export type Slug = string;

export interface Event {
  sessions?: Sessions;
  title?: Title1;
  slug?: Slug;
  [k: string]: any;
}
export interface Session {
  title?: Title;
  room?: Room;
  [k: string]: any;
}
